Allow additional YARP middleware to be specified
oidcproxydotnet/OidcProxy.Net pull request #187
Opened 2024-05-09 10:27 UTC by ihorwill

Resolves #186 

There us already a list for multiple YARP middleware handler types, i.e. `_yarpMiddlewareRegistrations` in `OidcProxy.Net.ModuleInitializers.IdpRegistration`, but no way to add extra types; only the built-in `TokenRenewalMiddleware` is added.

The approach taken in this PR is to add an `AddYarpMiddleware` method to `ProxyOptions`, collect the added types in a local list, and forward these types to `IdpRegistration` when `ProxyOptions.RegisterIdentityProvider` is called.

For this to work, the options callback needs to be called _before_ configuring YARP, in each of the adapters for OpenIdConnect, EntraId and Auth0.

The added YARO middleware needs to implement the `IYarpMiddleware` interface so this has been changed from `internal` to `public` to make it available.

2024-05-09 17:00 UTC, appie2go requested changes
Hi,

Thanks very much for taking to the time to contribute to this project. I appreciate it a lot! I've added some comments because I think there might be some issues with this PR (but we can fix them easily). 

Cheers,

Albert

Ps. I'll make sure the test-suite is more helpful! Thanks for the feedback!

2024-05-10 07:15 UTC, ihorwill commented on src/OidcProxy.Net/ModuleInitializers/IdpRegistrations.cs
> +    public void AddYarpMiddleware(Type handlerType)
That's much nicer. Will make that change.

2024-05-10 07:56 UTC, ihorwill commented on src/OidcProxy.Net/Middleware/IYarpMiddleware.cs
> +public interface IYarpMiddleware
I'm no expert on this kind of thing but it works well enough for me and feels natural. I'll add an XML comment on the interface now that it's public.

The client code seems pretty clean:

```cs
services.AddSingleton<MyYarpMiddleware>();

services.AddOidcProxy(oidcProxyConfig, options =>
{
    options.CookieName = "MyGatewayCookie";
    options.SetAllowedLandingPages(getConfiguredLandingPages());
    options.AddYarpMiddleware<MyYarpMiddleware>();
});
```

2024-05-10 08:14 UTC, ihorwill commented on src/OidcProxy.Net/Middleware/IYarpMiddleware.cs
> +public interface IYarpMiddleware
One thing that comes to mind is that the middleware we're adding here doesn't follow the usual .NET pattern:

```cs
internal class MyMiddleware
{
    private RequestDelegate Next { get; }

    public MyMiddleware(RequestDelegate next)
    {
        Next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        // Custom actions here
        await Next(context);
    }
}
```

I'm not sure if that could be made to work with the [registration code](https://github.com/oidcproxydotnet/OidcProxy.Net/blob/main/src/OidcProxy.Net/Middleware/WebApplicationExtensions.cs) though.

2024-05-12 12:57 UTC, merged