Add Keycloak spa+bff demo
oidcproxydotnet/OidcProxy.Net pull request #199
Opened 2024-05-18 15:47 UTC by ihorwill

Copy Auth0 demo, amend readme and make minor code changes to work with Keycloak.

2024-05-21 07:22 UTC, appie2go commented
Thanks very much, will look into this this afternoon!

2024-05-22 12:57 UTC, appie2go requested changes
Hi,

Thanks very much. This is very helpful. There are some minor details that need attention, I believe.

I was also hoping that maybe you have an idea on how we can provision an instance of key keycloak in a docker container, with SSL and everything?

Cheers,

2024-05-22 15:30 UTC, ihorwill commented
Thanks, I'll make amendments as noted and look into the Keycloak container idea.

2024-05-29 09:06 UTC, ihorwill commented on docs/demos/spa-bffs/keycloak/src/spa+bff/spa+bff.csproj
> +    <PackageReference Include="OidcProxy.Net.Auth0" Version="1.2.0" />
True! I guess it worked because the Auth0 package references OpenIdConnect. Fixed.

2024-05-29 09:46 UTC, ihorwill commented on docs/demos/spa-bffs/keycloak/src/spa+bff/appsettings.json
> +      "Domain": "{yourDomain}",
Removed Domain and updated readme.

2024-05-29 10:18 UTC, ihorwill commented
I've have not been able to get the SSL working with Keycloak in a container, and cannot pursue this further at the moment.

Please consider whether this PR has value with "a working Keycloak instance" as a precondition. Perhaps container setup instructions can be added separately at a later date?

Thanks and regards,
Ian

2024-05-30 11:20 UTC, appie2go commented
Hi Ian,

Yes.. The docker + SSL is quite some work. I'd love to merge your work. I will take some time to do so next week. I intend to fix the SSL issue myself then, I would love to share the solution with you because i assume it may be valuable to you?

Cheers,

Albert

2024-05-30 16:11 UTC, ihorwill commented
Hi Albert - sorry to dump that on you!

I'll certainly be interested in seeing it, but it won't be something I'll need to use, which is why I wasn't able to work on it during work hours ;-) When I originally had SSL trouble I ended up installing KC direct to my PC, and now our ITS has set up a "proper" instance for us to work with.

Kind regards,
Ian

2024-06-10 07:53 UTC, merged